spring:
  application:
    name: manada-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/manada
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # Flyway crea el esquema; Hibernate solo valida que coincida
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

manada:
  jwt:
    secret: "cambia-esto-por-un-secreto-largo-y-aleatorio-de-al-menos-32-caracteres"
    expiration-ms: 604800000   # 7 días
