package com.manada.backend.modules.bookings;

public enum ServiceType {
    VETERINARIA_GENERAL, URGENCIAS_24H, VACUNACION, CIRUGIA, ODONTOLOGIA,
    ESTETICA_BANO_CORTE, PASEO, GUARDERIA_HOSPEDAJE, ADIESTRAMIENTO, ESTERILIZACION
}
